project:
  type: website
  output-dir: docs

website:
  title: "Firuze İpek Yıldırım's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU430 - 2024 Fall" 
    border: true
format:
  html:
    toc: false
    # toc-location: left
    theme: lux
    #theme: superhero ve darkly vev lux bu da güzel
    css: styles.css
editor: visual 
