---
title: "Assignment 1"
---

# Assignment 1

```{r}
library(dslabs)

data("polls_us_election_2016")

head(polls_us_election_2016, 10)

total_na <- sum(is.na(polls_us_election_2016))
print(paste("Total number of NA values:", total_na))

birth_year <- 2004
first_name <- "Madina"

modified_poll_data <- polls_us_election_2016

for (i in seq_along(modified_poll_data)) {
  if (is.numeric(modified_poll_data[[i]])) {
    modified_poll_data[[i]][is.na(modified_poll_data[[i]])] <- birth_year
  } else if (is.character(modified_poll_data[[i]])) {
    modified_poll_data[[i]][is.na(modified_poll_data[[i]])] <- first_name
  } else if (is.factor(modified_poll_data[[i]])) {
    modified_poll_data[[i]] <- as.character(modified_poll_data[[i]])
    modified_poll_data[[i]][is.na(modified_poll_data[[i]])] <- first_name
    modified_poll_data[[i]] <- as.factor(modified_poll_data[[i]])
  }
}

head(modified_poll_data, 10)

total_na_modified <- sum(is.na(modified_poll_data))
print(paste("Total number of NA values in modified data:", total_na_modified))
```

My first assignment has two parts.

## ##a

In the lecture with Mustafa Baydogan, there are many alternatives to solve the problems that will occur in any job field we will be proceed into after graduation. We should begin by determining the problem and goals to achieve in order to optimize the situation. Even when dealing with Timber warpage estimation, it also includes the process that Industrial Engineers work with. It has different causes like knot points, distribution between old and young woods and etc. There are two data types: Structured and Unstructured. We use Traditional and Deep Learning with data sets in many fields like Online Retail, Machine Learning, and etc. In the video, Mustafa Baydogan explained different aspects of the connection between Industrial Engineering and data.

An Open Ended Question:

1\) What is the difference between Structured and Unstructured datas?

Answer: The Structured Data obtains discrete data types such as numbers, short text, and dates. The Unstructed Data data doesn't fit into a data table because its size or nature: for example, audio and video files and large text documents.

A Multiple Choice Question: 1) Which option is the one of the methods for Machine Learning?

a\) Preference Learning

b) Sales stock balance

c\) Website Design

d\) Website traffic monitoring

Answer is A.

### ##b

library(dslabs)

data("polls_us_election_2016")

head(polls_us_election_2016, 10)

total_na \<- sum(is.na(polls_us_election_2016)) print(paste("Total number of NA values:", total_na))

birth_year \<- 2004 first_name \<- "Madina"

modified_poll_data \<- polls_us_election_2016

for (i in seq_along(modified_poll_data)) { if (is.numeric(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- birth_year } else if (is.character(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name } else if (is.factor(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\] \<- as.character(modified_poll_data\[\[i\]\]) modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name modified_poll_data\[\[i\]\] \<- as.factor(modified_poll_data\[\[i\]\]) } }

head(modified_poll_data, 10)

total_na_modified \<- sum(is.na(modified_poll_data)) print(paste("Total number of NA values in modified data:", total_na_modified))

library(dslabs)

data("polls_us_election_2016")

head(polls_us_election_2016, 10)

total_na \<- sum(is.na(polls_us_election_2016)) print(paste("Total number of NA values:", total_na))

birth_year \<- 2004 first_name \<- "Madina"

modified_poll_data \<- polls_us_election_2016

for (i in seq_along(modified_poll_data)) { if (is.numeric(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- birth_year } else if (is.character(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name } else if (is.factor(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\] \<- as.character(modified_poll_data\[\[i\]\]) modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name modified_poll_data\[\[i\]\] \<- as.factor(modified_poll_data\[\[i\]\]) } }

head(modified_poll_data, 10)

total_na_modified \<- sum(is.na(modified_poll_data)) print(paste("Total number of NA values in modified data:", total_na_modified))

library(dslabs)

data("polls_us_election_2016")

head(polls_us_election_2016, 10)

total_na \<- sum(is.na(polls_us_election_2016)) print(paste("Total number of NA values:", total_na))

birth_year \<- 2004 first_name \<- "Madina"

modified_poll_data \<- polls_us_election_2016

for (i in seq_along(modified_poll_data)) { if (is.numeric(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- birth_year } else if (is.character(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name } else if (is.factor(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\] \<- as.character(modified_poll_data\[\[i\]\]) modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name modified_poll_data\[\[i\]\] \<- as.factor(modified_poll_data\[\[i\]\]) } }

head(modified_poll_data, 10)

total_na_modified \<- sum(is.na(modified_poll_data)) print(paste("Total number of NA values in modified data:", total_na_modified))

library(dslabs)

data("polls_us_election_2016")

head(polls_us_election_2016, 10)

total_na \<- sum(is.na(polls_us_election_2016)) print(paste("Total number of NA values:", total_na))

birth_year \<- 2004 first_name \<- "Madina"

modified_poll_data \<- polls_us_election_2016

for (i in seq_along(modified_poll_data)) { if (is.numeric(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- birth_year } else if (is.character(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name } else if (is.factor(modified_poll_data\[\[i\]\])) { modified_poll_data\[\[i\]\] \<- as.character(modified_poll_data\[\[i\]\]) modified_poll_data\[\[i\]\]\[is.na(modified_poll_data\[\[i\]\])\] \<- first_name modified_poll_data\[\[i\]\] \<- as.factor(modified_poll_data\[\[i\]\]) } }

head(modified_poll_data, 10)

total_na_modified \<- sum(is.na(modified_poll_data)) print(paste("Total number of NA values in modified data:", total_na_modified))
